name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Roda apenas quando há um push na branch main

jobs:
  deploy:
    name: Deploy to PythonAnywhere
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PA_HOST }}
          username: ${{ secrets.PA_USERNAME }}
          password: ${{ secrets.PA_PASSWORD }}
          script: |
            cd ~/bookstore
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            source ~/.virtualenvs/bookstore-env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            touch /var/www/joaovictorangelo_pythonanywhere_com_wsgi.py
